language: r

r:
#  - devel
  - release
sudo: FALSE
cache: packages

warnings_are_errors: TRUE

addons:
  apt:
    packages:
      - libv8-3.14-dev

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_packages: V8

r_github_packages:
  - jimhester/covr
  - dmenne/breathtestcore
  - dmenne/breathteststan

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function >> ~/.R/Makevars
  - echo "g++  -std=gnu++14 -fPIC" >> ~/.R/Makevars
  - echo ${CXX} --version

after_success:
  - travis_wait 59 Rscript -e 'covr::coveralls(line_exclusions="src/init.cpp")'
