# Assuming this file is in the directory
# docker-compose up . 
version: "3"
services:
  breathtestshiny:
    image: dmenne/breathtestshiny
    user: 'root'
    ports:
      - "3839:3838"
    volumes:
      - 'shiny_logs:/var/log/shiny-server'  
    restart: unless-stopped

volumes: 
   shiny_logs: