app <- ShinyDriver$new("../", seed = 1, phantomTimeout = 10000)
app$snapshotInit("default_demo_test")
app$setWindowSize(1200, 800)
app$setInputs(fit_method = "data_only",  timeout_ = 3000)
Sys.sleep(1)
app$snapshot()
app$setInputs(fit_method = "nls",  timeout_ = 3000)
app$snapshot()
app$setInputs(fit_method = "nlme",  timeout_ = 10000)
app$snapshot()
app$setInputs(fit_method = "stan",  timeout_ = 20000)
app$snapshot()

app$setInputs(samples_panel = "demo_panel", timeout_ = 10000)
Sys.sleep(1)
app$setInputs(data_source = "usz_13c_a", timeout_ = 20000)
app$snapshot()
app$setInputs(fit_method = "nls",  timeout_ = 10000)
app$snapshot()
